name: RAG QA Bot Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langchain huggingface_hub faiss-cpu pypdf tqdm

      - name: Run RAG bot
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python rag_bot.py
